In [1]:

%matplotlib inline
from opencage.geocoder import OpenCageGeocode
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import io
import requests
from io import StringIO
url="https://seanw2020.s3.amazonaws.com/CopyofweatherAUS.csv"
#s=requests.get(url).content
#c=pd.read_csv(io.StringIO(s.decode('utf-8')))

headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

df = pd.read_csv(data)
print(df)

             Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0       12/1/2008   Albury     13.4     22.9       0.6          NaN       NaN
1       12/2/2008   Albury      7.4     25.1       0.0          NaN       NaN
2       12/3/2008   Albury     12.9     25.7       0.0          NaN       NaN
3       12/4/2008   Albury      9.2     28.0       0.0          NaN       NaN
4       12/5/2008   Albury     17.5     32.3       1.0          NaN       NaN
...           ...      ...      ...      ...       ...          ...       ...
142188  6/20/2017    Uluru      3.5     21.8       0.0          NaN       NaN
142189  6/21/2017    Uluru      2.8     23.4       0.0          NaN       NaN
142190  6/22/2017    Uluru      3.6     25.3       0.0          NaN       NaN
142191  6/23/2017    Uluru      5.4     26.9       0.0          NaN       NaN
142192  6/24/2017    Uluru      7.8     27.0       0.0          NaN       NaN

       WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
0                W           44.0          W  ...        22.0       1007.7
1              WNW           44.0        NNW  ...        25.0       1010.6
2              WSW           46.0          W  ...        30.0       1007.6
3               NE           24.0         SE  ...        16.0       1017.6
4                W           41.0        ENE  ...        33.0       1010.8
...            ...            ...        ...  ...         ...          ...
142188           E           31.0        ESE  ...        27.0       1024.7
142189           E           31.0         SE  ...        24.0       1024.6
142190         NNW           22.0         SE  ...        21.0       1023.5
142191           N           37.0         SE  ...        24.0       1021.0
142192          SE           28.0        SSE  ...        24.0       1019.4

        Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0            1007.1       8.0       NaN     16.9     21.8         No      0.0
1            1007.8       NaN       NaN     17.2     24.3         No      0.0
2            1008.7       NaN       2.0     21.0     23.2         No      0.0
3            1012.8       NaN       NaN     18.1     26.5         No      1.0
4            1006.0       7.0       8.0     17.8     29.7         No      0.2
...             ...       ...       ...      ...      ...        ...      ...
142188       1021.2       NaN       NaN      9.4     20.9         No      0.0
142189       1020.3       NaN       NaN     10.1     22.4         No      0.0
142190       1019.1       NaN       NaN     10.9     24.5         No      0.0
142191       1016.8       NaN       NaN     12.5     26.1         No      0.0
142192       1016.5       3.0       2.0     15.1     26.0         No      0.0

        RainTomorrow
0                 No
1                 No
2                 No
3                 No
4                 No
...              ...
142188            No
142189            No
142190            No
142191            No
142192            No

[142193 rows x 24 columns]

In [3]:
df.dropna(how='any', inplace=True)

#df.drop(['B', 'C'], axis=1)


df['RainTomorrow'] = df['RainTomorrow'].replace(to_replace=['No', 'Yes'], value=[0, 1])
df['RainToday'] = df['RainToday'].replace(to_replace=['No', 'Yes'], value=[0, 1])

df.head(100)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
5939,1/1/2009,Cobar,17.9,35.2,0.0,12.0,12.3,SSW,48.0,ENE,...,13.0,1006.3,1004.4,2.0,5.0,26.6,33.4,0,0.0,0
5940,1/2/2009,Cobar,18.4,28.9,0.0,14.8,13.0,S,37.0,SSE,...,8.0,1012.9,1012.1,1.0,1.0,20.3,27.0,0,0.0,0
5942,1/4/2009,Cobar,19.4,37.6,0.0,10.8,10.6,NNE,46.0,NNE,...,22.0,1012.3,1009.2,1.0,6.0,28.7,34.9,0,0.0,0
5943,1/5/2009,Cobar,21.9,38.4,0.0,11.4,12.2,WNW,31.0,WNW,...,22.0,1012.7,1009.1,1.0,5.0,29.1,35.6,0,0.0,0
5944,1/6/2009,Cobar,24.2,41.0,0.0,11.2,8.4,WNW,35.0,NW,...,15.0,1010.7,1007.4,1.0,6.0,33.6,37.6,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6037,4/9/2009,Cobar,17.1,28.7,0.0,6.6,5.5,WNW,43.0,ENE,...,32.0,1021.2,1016.9,7.0,7.0,20.1,26.7,0,14.4,1
6038,4/10/2009,Cobar,16.5,20.6,14.4,6.0,0.0,E,30.0,NE,...,76.0,1021.3,1019.3,7.0,7.0,16.9,19.9,1,2.4,1
6039,4/11/2009,Cobar,16.0,24.4,2.4,0.2,4.7,ENE,31.0,NNW,...,63.0,1023.1,1020.2,7.0,5.0,17.6,24.0,1,5.4,1
6040,4/12/2009,Cobar,16.8,23.9,5.4,2.4,4.2,NNE,20.0,ENE,...,68.0,1022.9,1020.2,7.0,5.0,18.5,22.9,1,0.0,0
6041,4/13/2009,Cobar,16.2,23.9,0.0,1.8,4.4,ENE,24.0,ESE,...,71.0,1020.6,1016.4,7.0,7.0,18.9,22.1,0,0.4,0

In [4]:
#df = df.drop(['WindGustDir'])
#df = df.drop(['Date'], axis=1)
#df.head()
#dftomorrow = df
#df = df.drop("RainTomorrow", axis=1)
#df
df['month'] = pd.DatetimeIndex(df['Date']).month
df['year'] = pd.DatetimeIndex(df['Date']).year
df['day'] = pd.DatetimeIndex(df['Date']).day
df = df.drop(['Date'], axis=1)

df.head()

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow,month,year,day
5939,Cobar,17.9,35.2,0.0,12.0,12.3,SSW,48.0,ENE,SW,...,2.0,5.0,26.6,33.4,0,0.0,0,1,2009,1
5940,Cobar,18.4,28.9,0.0,14.8,13.0,S,37.0,SSE,SSE,...,1.0,1.0,20.3,27.0,0,0.0,0,1,2009,2
5942,Cobar,19.4,37.6,0.0,10.8,10.6,NNE,46.0,NNE,NNW,...,1.0,6.0,28.7,34.9,0,0.0,0,1,2009,4
5943,Cobar,21.9,38.4,0.0,11.4,12.2,WNW,31.0,WNW,WSW,...,1.0,5.0,29.1,35.6,0,0.0,0,1,2009,5
5944,Cobar,24.2,41.0,0.0,11.2,8.4,WNW,35.0,NW,WNW,...,1.0,6.0,33.6,37.6,0,0.0,0,1,2009,6

In [5]:

#df = df.drop(['Location'], axis=1)
#df = df.drop(['WindGustDir'], axis =1)
#df.head()

In [9]:
##locations = df['Location'].unique()
##print(locations)

['Cobar' 'CoffsHarbour' 'Moree' 'NorfolkIsland' 'Sydney' 'SydneyAirport'
 'WaggaWagga' 'Williamtown' 'Canberra' 'Sale' 'MelbourneAirport'
 'Melbourne' 'Mildura' 'Portland' 'Watsonia' 'Brisbane' 'Cairns'
 'Townsville' 'MountGambier' 'Nuriootpa' 'Woomera' 'PerthAirport' 'Perth'
 'Hobart' 'AliceSprings' 'Darwin']

In [24]:


key = "65353eadce2c4d4ca46678d5cf8ad5f6"  # get api key from:  https://opencagedata.com



	
geocoder = OpenCageGeocode(key)


	
query = 'CoffsHarbour, Australia' 


	
results = geocoder.geocode(query)


	
print (results)

[{'annotations': {'DMS': {'lat': "30° 18' 49.26240'' S", 'lng': "153° 4' 7.15152'' E"}, 'MGRS': '56JNM0660046453', 'Maidenhead': 'QF69mq84fr', 'Mercator': {'x': 17039524.527, 'y': -3522371.83}, 'OSM': {'note_url': 'https://www.openstreetmap.org/note/new#map=17/-30.31368/153.06865&layers=N', 'url': 'https://www.openstreetmap.org/?mlat=-30.31368&mlon=153.06865#map=17/-30.31368/153.06865'}, 'UN_M49': {'regions': {'AU': '036', 'AUSTRALASIA': '053', 'OCEANIA': '009', 'WORLD': '001'}, 'statistical_groupings': ['MEDC']}, 'callingcode': 61, 'currency': {'alternate_symbols': ['A$'], 'decimal_mark': '.', 'disambiguate_symbol': 'A$', 'html_entity': '$', 'iso_code': 'AUD', 'iso_numeric': '036', 'name': 'Australian Dollar', 'smallest_denomination': 5, 'subunit': 'Cent', 'subunit_to_unit': 100, 'symbol': '$', 'symbol_first': 1, 'thousands_separator': ','}, 'flag': '🇦🇺', 'geohash': 'r6sge1t1ypsrdjcmv435', 'qibla': 278.63, 'roadinfo': {'drive_on': 'left', 'speed_in': 'km/h'}, 'sun': {'rise': {'apparent': 1593809160, 'astronomical': 1593804060, 'civil': 1593807600, 'nautical': 1593805800}, 'set': {'apparent': 1593759480, 'astronomical': 1593764580, 'civil': 1593761040, 'nautical': 1593762840}}, 'timezone': {'name': 'Australia/Sydney', 'now_in_dst': 0, 'offset_sec': 36000, 'offset_string': '+1000', 'short_name': 'AEST'}, 'what3words': {'words': 'inhibition.future.geothermal'}}, 'components': {'ISO_3166-1_alpha-2': 'AU', 'ISO_3166-1_alpha-3': 'AUS', '_category': 'road', '_type': 'road', 'city': 'NORTH BOAMBEE VALLEY', 'continent': 'Oceania', 'country': 'Australia', 'country_code': 'au', 'postcode': '2450', 'state': 'NEW SOUTH WALES', 'state_code': 'NSW', 'street': 'ENGLANDS RD'}, 'confidence': 10, 'formatted': 'ENGLANDS RD, NORTH BOAMBEE VALLEY NSW 2450, Australia', 'geometry': {'lat': -30.313684, 'lng': 153.0686532}}, {'annotations': {'DMS': {'lat': "25° 0' 0.00000'' S", 'lng': "135° 0' 0.00000'' E"}, 'MGRS': '53JNN0000035052', 'Maidenhead': 'PG75ma00aa', 'Mercator': {'x': 15028131.257, 'y': -2857692.611}, 'OSM': {'note_url': 'https://www.openstreetmap.org/note/new#map=17/-25.00000/135.00000&layers=N', 'url': 'https://www.openstreetmap.org/?mlat=-25.00000&mlon=135.00000#map=17/-25.00000/135.00000'}, 'UN_M49': {'regions': {'AU': '036', 'AUSTRALASIA': '053', 'OCEANIA': '009', 'WORLD': '001'}, 'statistical_groupings': ['MEDC']}, 'callingcode': 61, 'currency': {'alternate_symbols': ['A$'], 'decimal_mark': '.', 'disambiguate_symbol': 'A$', 'html_entity': '$', 'iso_code': 'AUD', 'iso_numeric': '036', 'name': 'Australian Dollar', 'smallest_denomination': 5, 'subunit': 'Cent', 'subunit_to_unit': 100, 'symbol': '$', 'symbol_first': 1, 'thousands_separator': ','}, 'flag': '🇦🇺', 'geohash': 'r581b0bh2n0p0581b0bh', 'qibla': 287.68, 'roadinfo': {'drive_on': 'left', 'speed_in': 'km/h'}, 'sun': {'rise': {'apparent': 1593812820, 'astronomical': 1593807900, 'civil': 1593811320, 'nautical': 1593809580}, 'set': {'apparent': 1593764520, 'astronomical': 1593769380, 'civil': 1593766020, 'nautical': 1593767700}}, 'timezone': {'name': 'Australia/Darwin', 'now_in_dst': 0, 'offset_sec': 34200, 'offset_string': '+0930', 'short_name': 'ACST'}, 'what3words': {'words': 'spaceship.clicking.pacts'}}, 'bounds': {'northeast': {'lat': -9.142917, 'lng': 162.0}, 'southwest': {'lat': -55.273308, 'lng': 112.5}}, 'components': {'ISO_3166-1_alpha-2': 'AU', 'ISO_3166-1_alpha-3': 'AUS', '_category': 'place', '_type': 'country', 'continent': 'Oceania', 'country': 'Australia', 'country_code': 'au'}, 'confidence': 1, 'formatted': 'Australia', 'geometry': {'lat': -25.0, 'lng': 135.0}}]

In [26]:


locations = df['Location'].unique()

list_lat = []   # create empty lists

list_long = []

counter = 0

	

for loc in locations: # iterate over rows in dataframe
    
    


    query = str(loc) + ', Australia'

    result = geocoder.geocode(query) 


    lat = result[0]['geometry']['lat']
    long = result[0]['geometry']['lng']

    list_lat.append(lat)
    list_long.append(long)

 
	
print(list_lat)
print(list_long)
# create new columns from lists    

#df_crime_more_cities['lat'] = list_lat   

#df_crime_more_cities['lon'] = list_long

[-31.4983333, -30.313684, -29.4617202, -25.0, -33.8548157, -33.8897813, -35.0945116, -32.815, -35.2975906, -38.106605, -37.6699993, -37.8142176, -34.1847265, -38.363435, -37.7110022, -27.4689682, -16.9206657, -19.2569391, -37.9090923, -34.4693354, -31.1999142, -31.9514339, -31.9527121, -42.8825088, -23.6968054, -12.46044]
[145.8344444, 153.0686532, 149.8407153, 135.0, 151.2164539, 150.7107643, 147.3606631, 151.8427778, 149.1012676, 147.0679453, 144.8187136, 144.9631608, 142.1624972, 141.6056055, 145.083635, 153.0234991, 145.7721854, 146.8239537, 140.8279513, 138.9939006, 136.8253532, 115.9516469, 115.8604796, 147.3281233, 133.8787127, 130.8410469]

In [6]:
# Assign X (data) and y (target)
X = df.drop("RainToday", axis=1)
y = df["RainToday"]
print(X.shape, y.shape)

(56420, 25) (56420,)

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [8]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
classifier.fit(X_train, y_train)
#X_train.head()

ValueError: could not convert string to float: 'NE'